### PR TITLE
upgrade to net5.0

### LINKED ISSUE #33: bump dotnet core to net5.0

### PR DESCRIPTION
**Pull request by adamszcz**
# What I added (link any issues addressed)
Closes #33 
# How to test it
Should run the same after running ```dotnet restore```

### CODE REVIEW

**Comment by adamszcz** [comment]
Hmmm I didn't have this issue on my end.

**Comment by adamszcz** [comment]
Looks like you need to upgrade our pipeline to .NET 5.0

```
 ! [remote rejected] upgradeToDotnet5 -> upgradeToDotnet5 (refusing to allow an OAuth App to create or update workflow `.github/workflows/run-tests.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/cszczepaniak/cribbly-backend.git'
> git log --oneline --cherry upgradeToDotnet5...upgradeToDotnet5@{upstream} --
> git pull --tags origin upgradeToDotnet5
```

**Comment by cszczepaniak** [comment]
@adamszcz I had taken care of this in my PR that's been open for a while. We can either take this PR (with the pipeline fixed) as a smaller incremental change, or try to get my other one merged

**Comment by adamszcz** [comment]
Let's merge your older PR. What can I do to help?

**Pull request closed without merging**
