### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by cszczepaniak**
# What I added (link any issues addressed)
Oh boy. Sorry in advance; this is gonna be one heck of a diff.

Basically, I didn't like how we had things organized. In the last few months, I've seen the benefits of arranging things by _domain_ rather than by function. Instead of a `Services/` folder, I find it cleaner to have a `Games/` folder with `Services/`, `Models/`, etc. inside of it. That way when you care about only a certain part of the domain, you have everything in one spot. This is advantageous because generally when you change one thing about a game model, you'll have to also touch repositories, services, and all the rest.

I also bumped us to .NET5 since it's supposedly _blazingly_ fast, and we get some new language features for free.

I also fixed an issue with migrations; the last one added was causing issues when starting with a completely empty DB.

I also built a little abstraction to separate our SQL queries from our repositories in a bit of a cleaner way.

# How to test it
Everything should still work the way it's supposed to...

### CODE REVIEW

**Comment by cszczepaniak** [comment]
@adamszcz I will let you merge #21 before we think about this one. It'll be much easier to resolve the conflicts on this end.

**Comment by cszczepaniak** [comment]
Probably need to tell the build machine that we need .NET5 now...

**Comment by adamszcz** [comment]
Sorry it took so long for me to look at this one. I just pulled it up, ran ```dotnet clean``` and ```dotnet restore```, but it looks like many of the namespaces don't know about each other. For example, in ```Startup.cs``` the class does not know anything about our data access project. Am I missing something?

**Comment by cszczepaniak** [comment]
@adamszcz A couple things - I'm still working on stuff a bit so it's potentially a bit broken. Also you probably have to `dotnet restore src/CribblyBackend`. Also I bumped to dotnet 5 so make sure you have that SDK installed

**Comment by adamszcz** [comment]
Ahhh that makes sense. I was going to say, I found that I have the ```CribblyBackend``` folder as well as ```CribblyBackend.Core```, which the classes seem to now be referencing, so I will let you get this one solidified before I try to get it working on my end.

**Comment by cszczepaniak** [comment]
@adamszcz Can you check this one again? I made a few fixes here, plus I'd like to be on the latest dotnet core version. It probably makes sense to get this one in before we start doing much more with the backend.

**Comment by adamszcz** [comment]
Shit, sorry man - I just saw your comment from 2 weeks ago. Looking at this now

**Comment by adamszcz** [comment]
So, this seems to work, but it looks like all of the GET endpoints aren't working on my end if something contains a Division. Must be a foreign key thing? Either way, I can approve this and get the domain changes merged though

**Review by adamszcz — APPROVED** [review]

**Pull request merged**
